src/Entity/Event.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
#[ApiResource]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $nbr_vote;

    #[ORM\Column(type: 'boolean')]
    private $is_archived;

    #[ORM\Column(type: 'date')]
    private $date_end_vote;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToMany(targetEntity: GroupMail::class, inversedBy: 'events')]
    #[ORM\JoinTable(name: "groupMailByEvent")]
    private $groupMails;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: OptionDateEvent::class)]
    private $optionDateEvent;

    #[ORM\ManyToOne(targetEntity: CategotyEvent::class, inversedBy: 'events')]
    private $categoryEvent;

    public function __construct()
    {
        $this->groupMails = new ArrayCollection();
        $this->optionDateEvent = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbrVote(): ?string
    {
        return $this->nbr_vote;
    }

    public function setNbrVote(?string $nbr_vote): self
    {
        $this->nbr_vote = $nbr_vote;

        return $this;
    }

    public function isIsArchived(): ?bool
    {
        return $this->is_archived;
    }

    public function setIsArchived(bool $is_archived): self
    {
        $this->is_archived = $is_archived;

        return $this;
    }

    public function getDateEndVote(): ?\DateTimeInterface
    {
        return $this->date_end_vote;
    }

    public function setDateEndVote(\DateTimeInterface $date_end_vote): self
    {
        $this->date_end_vote = $date_end_vote;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, GroupMail>
     */
    public function getGroupMails(): Collection
    {
        return $this->groupMails;
    }

    public function addGroupMail(GroupMail $groupMail): self
    {

            $this->groupMails[] = $groupMail;


        return $this;
    }

    public function removeGroupMail(GroupMail $groupMail): self
    {
        $this->groupMails->removeElement($groupMail);

        return $this;
    }

    /**
     * @return Collection<int, OptionDateEvent>
     */
    public function getOptionDateEvent(): Collection
    {
        return $this->optionDateEvent;
    }

    public function addOptionDateEvent(OptionDateEvent $optionDateEvent): self
    {
        if (!$this->optionDateEvent->contains($optionDateEvent)) {
            $this->optionDateEvent[] = $optionDateEvent;
            $optionDateEvent->setEvent($this);
        }

        return $this;
    }

    public function removeOptionDateEvent(OptionDateEvent $optionDateEvent): self
    {
        if ($this->optionDateEvent->removeElement($optionDateEvent)) {
            // set the owning side to null (unless already changed)
            if ($optionDateEvent->getEvent() === $this) {
                $optionDateEvent->setEvent(null);
            }
        }

        return $this;
    }

    public function getCategoryEvent(): ?CategotyEvent
    {
        return $this->categoryEvent;
    }

    public function setCategoryEvent(?CategotyEvent $categoryEvent): self
    {
        $this->categoryEvent = $categoryEvent;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description',TextareaType::class)
            ->add('date_end_vote')
            ->add('optionDateEvent',ChoiceType::class);





    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\CategotyEvent;
use App\Entity\Event;
use App\Entity\OptionDateEvent;
use App\Form\CategotyEventType;
use App\Form\EventType;
use App\Form\OptionDateEventType;
use App\Repository\CategotyEventRepository;
use App\Repository\EventRepository;
use App\Repository\GroupMailRepository;
use App\Repository\OptionDateEventRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\Date;

#[Route('/event')]
class EventController extends AbstractController
{
    private $security;
    private $categotyEventRepository;
    private $groupMailRepository;

    public function __construct(Security $security, CategotyEventRepository $categotyEventRepository, GroupMailRepository $groupMailRepository)
    {
        $this->security = $security;
        $this->categotyEventRepository =$categotyEventRepository;
        $this->groupMailRepository = $groupMailRepository;
    }
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EventRepository $eventRepository,OptionDateEventRepository $optionDateEventRepository, GroupMailRepository $groupMailRepository, CategotyEventRepository $categotyEventRepository): Response
    {
        if ($request->isXmlHttpRequest()) {
            $optionsDateEvent =json_decode($request->request->get("optionDateEvent"), true) ;
            $groupMails = json_decode($request->request->get("groupMails"), true) ;
            $event = new Event();
            $event->setUser($this->security->getUser());
            $event->setIsArchived(false);
            $event->setNbrVote(0);
            $event->setCategoryEvent($categotyEventRepository->find($request->request->get("categoryEvent")));
            $event->setName($request->request->get("name"));
            $event->setDescription($request->request->get("description"));
            $event->setDateEndVote(new \DateTime($request->request->get("dateEndVote")));


            foreach ($groupMails as $item){
                $event->addGroupMail( $groupMailRepository->find($item));
            }
            $eventRepository->add($event, true);
            foreach ($optionsDateEvent as $item){
                $optionDateEvent = new OptionDateEvent();
                $optionDateEvent->setNbrVote(0);
                $optionDateEvent->setOptionDate(new \DateTime($item));
                $optionDateEvent->setEvent($eventRepository->find($event));
                $event->addOptionDateEvent($optionDateEvent);
                $optionDateEventRepository->add($optionDateEvent,true);
            }

            return $this->json(['event' => $eventRepository->find($event)->getId()]);
        }
        return $this->renderForm('event/new.html.twig', [
            'groupmails' => $this->groupMailRepository->findAll(),
            'categoryEvents' => $this->categotyEventRepository->findAll(),


        ]);
    }

    #[Route('/eventTo', name: 'app_event_to', methods: ['GET'])]
    public function eventTo(Request $request, EventRepository $eventRepository,OptionDateEventRepository $optionDateEventRepository, GroupMailRepository $groupMailRepository, CategotyEventRepository $categotyEventRepository): Response
    {
        $IdsGroupmail = '(';
         $groupMails=$groupMailRepository->findByUser($this->security->getUser());
         foreach ($groupMails as $item){
             $IdsGroupmail  .= $item->getId().',';
         }
        $IdsGroupmail = trim($IdsGroupmail,',');
        $IdsGroupmail .=')';
        $eventInvited = $eventRepository->findByGroupMail($IdsGroupmail);
        return $this->render('event/event_to.html.twig', [
            'events' => $eventInvited,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(EventRepository $eventRepository,Request $request ): Response
    {
        $event = $eventRepository->find($request->get('id'));
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(ManagerRegistry $doctrine,Request $request, EventRepository $eventRepository,OptionDateEventRepository $optionDateEventRepository, GroupMailRepository $groupMailRepository, CategotyEventRepository $categotyEventRepository): Response
    {
        $entityManager = $doctrine->getManager();
        $event = $entityManager->getRepository(Event::class)->find($request->get('id'));
        if ($request->isXmlHttpRequest()) {
            $entityManager = $doctrine->getManager();
            $optionsDateEvent = json_decode($request->request->get("optionDateEvent"), true);
            $groupMails = json_decode($request->request->get("groupMails"), true);
            $event->setCategoryEvent($categotyEventRepository->find($request->request->get("categoryEvent")));
            $event->setName($request->request->get("name"));
            $event->setDescription($request->request->get("description"));
            $event->setDateEndVote(new \DateTime($request->request->get("dateEndVote")));


            foreach ($groupMails as $item) {
                if( !in_array($groupMailRepository->find($item),$event->getGroupMails()->getValues()))
                $event->addGroupMail($groupMailRepository->find($item));
            }

            foreach ($event->getGroupMails()->getValues()as $item) {
                if( !in_array($item->getId(),$groupMails ))
                    $event->removeGroupMail($item);
            }
            $entityManager->flush();
            foreach ($optionsDateEvent as $item) {
                if(!in_array($optionDateEventRepository->findOneBy(['optionDate'=>new \DateTime($item)]),$event->getOptionDateEvent()->getValues())){
                    $optionDateEvent = new OptionDateEvent();
                    $optionDateEvent->setNbrVote(0);
                    $optionDateEvent->setOptionDate(new \DateTime($item));
                    $optionDateEvent->setEvent($eventRepository->find($event));
                    $event->addOptionDateEvent($optionDateEvent);
                    $optionDateEventRepository->add($optionDateEvent, true);
                }

            }
            foreach ($event->getOptionDateEvent()->getValues() as $item) {
                if(!in_array(date_format($item->getOptionDate(),"m/d/Y"),$optionsDateEvent)){
                    $event->removeOptionDateEvent($item);
                    $optionDateEventRepository->remove($item, true);
                }


            }
            return $this->json(['event' => $eventRepository->find($event)->getId()]);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' =>$event,

            'groupmails' => $this->groupMailRepository->findAll(),
            'categoryEvents' => $this->categotyEventRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, EventRepository $eventRepository, OptionDateEventRepository $optionDateEventRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$request->get('id'), $request->request->get('_token'))) {
            $optionDateEventRepository->removeByEvent($request->get('id'));
            $eventRepository->remove($eventRepository->find($request->get('id')), true);
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }

    private function getEventCategorieOptions(){
        $categotyEvent = $this->categotyEventRepository->findAll();
        $categotyEventOptions = [];
        foreach ($categotyEvent as $index){
            $categotyEventOptions[] = [$index->getNom() => $index];
        }
        return $categotyEventOptions;
    }
    private function getGroupMailOptions(){
        $groupMail = $this->groupMailRepository->findAll();
        $groupMailOptions = [];
        foreach ($groupMail as $index){
            $groupMailOptions[] = [$index->getName() => $index];
        }
        return $groupMailOptions;
    }


}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger"> Delete</button>
</form>

templates/event/_form.html.twig
<div class="container">
    <form id="formEvent" method="post" >
    <div class="row">
        <div class="col-4">
            <label for="inputCategoryEvent" class="required"> Name event :</label>
            <input type="text" class="form-control" id="inputName" value="{% if event is defined  %} {{ event.name }}{% endif %}" name="inputName" required autofocus>
        </div>
        <div class="col-4">
            <label for="inputCategoryEvent" class="required"> Category event :</label>

            <select class="form-select" id="inputCategoryEvent" name="inputCategoryEvent" >
                <option selected>Open this select menu</option>
                {% for categoryEvent in categoryEvents %}
                    {% if event is defined  %}
                    <option value={{ categoryEvent.id }} {% if event.categoryEvent.id == categoryEvent.id %}  selected {% endif %}>{{ categoryEvent.nom }}</option>
                    {% else %}
                     <option value={{ categoryEvent.id }}>{{ categoryEvent.nom }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <a href="/categoty/events/new"> <i class="fa fa-plus"></i>Ajouter category</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-4">
            <label for="endvote" class="required"> Fin vote :</label>
            <input type= "text" id="datepickerend" class="form-control" value="{% if event is defined  %} {{ event.getDateEndVote()|date("m/d/Y") }}{% endif %}" id="endvote" name="endvote">
        </div>
        <div class="col-4">
            <label for="event_date" class="form-label">Date évènement</label>
            <div class="row">
                <div class="col">
                    <input type= "text" id="datepicker" class="form-control" >
                </div>
                <div class="col-1">
                    <button type="button" class="btn btn-icon btn-secondary " id="buttontest">
                        <i class="fa fa-solid fa-plus"></i>
                    </button>
                </div>
            </div>
            <br>
            <select class="form-select" id="event_optionDateEvent" name="event_optionDateEvent" multiple>
                {% if event is defined  %}
                    {% for item in event.getOptionDateEvent().getValues() %}
                    <option selected>{{item.optionDate|date("m/d/Y") }}</option>
                    {% endfor %}
                {% endif %}
            </select>
        </div>

    </div>
    <br>
    <div class="row">
        <div class="col-4">

            <label for="inputgroupMails" class="required"> Group mails :</label>
            <select class="form-select" multiple id="inputgroupMails" name="inputgroupMails">
                {% for groupmail in groupmails %}
                    {% if event is defined  %}
                    <option value={{ groupmail.id }} {% for item in  event.getGroupMails().getValues() %}{% if groupmail.id == item.id %} selected {% endif %}{% endfor%} >{{ groupmail.name }}</option>
                    {% else %}
                     <option value={{ groupmail.id }}>{{ groupmail.name }}</option>
                     {% endif %}
                {% endfor %}
            </select>
            <a href="/group/mail/new"> <i class="fa fa-plus"></i>Ajouter Groupe mail</a>

        </div>
        <div class="col-4">
            <label for="inputDescription" class="required"> Description :</label>
            <textarea   class="form-control" multiple id="inputDescription" name="inputDescription">{% if event is defined  %}{{ event.description }}{% endif %}</textarea>
        </div>
    </div>

    </form>
    <br>
    <div class="row">
        <div class="col">
    <button class="btn btn-primary " id={% if event is defined %}"updateEvent">Modifier{% else %}"addEvent" >Ajouter{% endif %}</button>
        </div>
        <div class="col">
    {% if event is defined %}
    {{ include('event/_delete_form.html.twig') }}
    {% endif %}
        </div>
    </div>
</div>
</div>

templates/event/edit.html.twig
{% extends 'layout/base.html.twig' %}
{% block title %}Edit Event{% endblock %}

{% block body %}
<div class="content-form">
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_event_index') }}">back to list</a>


</div>
{% endblock %}

templates/event/event_to.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}List Events{% endblock %}

{% block body %}
    <div class="content-form">
        <h1>Vos événement </h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Nombre des votes</th>
                <th>Date fin du vote</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td>{{ event.id }}</td>
                    <td>{{ event.name }}</td>
                    <td>{{ event.description }}</td>
                    <td>{{ event.nbrVote }}</td>
                    <td>{{ event.dateEndVote ? event.dateEndVote|date('Y-m-d') : '' }}</td>
                    <td>
                        <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a>
                        <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}List Events{% endblock %}

{% block body %}
    <div class="content-form">
    <h1>Vos événement </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Nombre des votes</th>
                <th>Date fin du vote</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.name }}</td>
                <td>{{ event.description }}</td>
                <td>{{ event.nbrVote }}</td>
                <td>{{ event.dateEndVote ? event.dateEndVote|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a>
                    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_event_new') }}">Create new</a>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'layout/base.html.twig' %}
{% block title %}Create Event{% endblock %}


{% block body %}
<div class="content-form">
    <h1>Création d'un évènement </h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('app_event_index') }}">back to list</a>
</div>
{% endblock %}

templates/event/show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
<div class="content-form">
    <h1>Event</h1>
<div class="row">
    <table class="table col">
        <tbody>

            <tr>
                <th>Name</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Nombre Votes</th>
                <td>{{ event.nbrVote }}</td>
            </tr>
            <tr>
                <th>Date_end_vote</th>
                <td>{{ event.dateEndVote ? event.dateEndVote|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    {% set foo = 0 %}
{% for item in  event.getGroupMails().getValues%}
    {% set foo = foo+item.getUsers().getValues()|length %}
{% endfor %}

    <div class=" col">
            <div class="panel-heading ">
                <b class="panel-title">
                    Date Possible de l'event</b>
            </div>
        <br>
        {% for item in event.getOptionDateEvent().getValues() %}
        <div class="progress">
            <input type="checkbox" value="">

                            <div class="progress-bar progress-bar-striped " role="progressbar" style="width: {{ (item.nbrVote*100)/foo }}%" >

                                {{ item.nbrVote }}
                            </div>
            <div class="col" style="padding-top: 10px">{{ item.getOptionDate()|date('j F  Y') }}</div>

        </div>
        <br>
        {% endfor %}
        <div class="panel-footer text-center">
                <button type="button" class="btn btn-success btn-block btn-sm">
                    Vote</button>
            </div>
    </div>

</div>
    <a href="{{ path('app_event_index') }}">back to list</a>

    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
</div>
{% endblock %}